### PR TITLE
Initial diagrams for canvas-with-time

### PR DESCRIPTION
**Pull request by azaroth42**
Add some initial diagrams about the canvas with time notion to the repo, along with Omnigraffle source.

### CODE REVIEW

**Comment by azaroth42** [comment]
Testing slack integration...

**Comment by jpstroop** [comment]
One more slack test

**Comment by jpstroop** [comment]
:+1: to getting these under version control

**Comment by zimeon** [comment]
:+1: great start and certainly want under version control

**Comment by jpstroop** [comment]
Nothing normative here. Merging.

**Comment by zimeon** [comment]
I added to todays call agenda the question of how we deal with pull requests here -- for spec stuff it should probably be editors, but are we going to collect more that just a first draft in this repo?

**Pull request merged**
